//! Writes the reference ICC profiles the fixtures are tagged with.
//!
//! Run from the repository root:
//!
//! ```sh
//! cargo run --quiet --example make-icc -- test_images/display-p3.icc
//! ```
//!
//! The profile is checked in rather than generated by `test_images/generate.sh`,
//! so that regenerating the fixtures needs nothing but ImageMagick and Python.

fn main() {
    let path = std::env::args()
        .nth(1)
        .expect("usage: make-icc <output.icc>");
    let mut profile = moxcms::ColorProfile::new_display_p3()
        .encode()
        .expect("Display P3 encodes");

    // ICC requires the profile size to be a multiple of four, and `moxcms`
    // stops at the last tag — 598 bytes for this one. libpng enforces the
    // rule and refuses the whole `iCCP` chunk without it, so pad with the
    // zeroes the spec asks for and restate the size in the header.
    while !profile.len().is_multiple_of(4) {
        profile.push(0);
    }
    let size = (profile.len() as u32).to_be_bytes();
    profile[..4].copy_from_slice(&size);

    // The header's PCS illuminant is fixed by the specification at D50, and
    // `moxcms` writes its own rounding of it. Anything reading the profile
    // strictly — libpng again — treats that as a malformed header.
    const D50: [u8; 12] = [
        0x00, 0x00, 0xf6, 0xd6, 0x00, 0x01, 0x00, 0x00, 0x00, 0x00, 0xd3, 0x2d,
    ];
    profile[68..80].copy_from_slice(&D50);

    std::fs::write(&path, profile).expect("writing the profile");
}
